name = "YA(N)A"
author = "Qiinr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "975c9a9e5c9b40c3f4fa3053d4e8d5abd5af5b368fc5f3dbca5dcd23f1a59167"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
