name = "YA(N)A"
author = "Qiinr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2168ebf8662b8c2daf22ab1f9019f0db9935d2262a4e0450abd86d261d998f37"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
