name = "YA(N)A"
author = "Qiinr"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd3bba7a18b537fb3bbdcf4d21cc1c7a81af41207ca4912fb6fa857c55c1d44d"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
